### PR TITLE
fix: update urls to point to main branch

### PR DESCRIPTION
**Pull request by diogomatsubara**

### CODE REVIEW

**Review by fuzzypixelz — COMMENTED** [review]
There are some remaining `master` references in the blog, do we want to rename those too?

**Comment by diogomatsubara** [comment]
@fuzzypixelz since those are historical, I left them out. Not sure if we should update the blog posts after they are published

**Comment by fuzzypixelz** [comment]
> @fuzzypixelz since those are historical, I left them out. Not sure if we should update the blog posts after they are published

I would argue that:

1. Calling them historical is misleading since people might still read the them today (at least _I_ do refer to them from time to time).
2. If someone reads them today then they get directed to `master`; a version of the repository which doesn't match the date of publication. If doesn't match the publication date, then it should at least match the "current" date. `master` is an awkward place in between.

**Comment by diogomatsubara** [comment]
@fuzzypixelz updated the blog posts as well.

**Pull request merged**
